Fixing debugger scripts (#1120)
GDB/LLDB has been broken for a while, and I suspect it has been broken
since PR #1000.

When `k start` was typed in GDB, we had the following error when
pretty-printing the subject:
```Bash
Temporary breakpoint 1, 0x00005555555c00f0 in main ()
0x00005555555bb080 in k_step (subject=Traceback (most recent call last):
  File "<string>", line 392, in to_string
  File "<string>", line 599, in append
  File "<string>", line 381, in isSymbolABinder
AttributeError: 'NoneType' object has no attribute 'value'

Python Exception <class 'AttributeError'>: 'NoneType' object has no attribute 'value'
) at /home/robertorosmaninho/pi2-inc/tests/add-rewrite.k:20
20        rule [state-succ] : s(M:Nat) ~> state(N:Nat, _:Nat) => state(N, s(M))
(gdb)
```
This happens due to the renaming of `table_getSymbolNameForTag` and
other global symbols to follow a unique snake_case pattern not being
reflected on these debug scripts.

The same should be applied to lldb. But honestly not tested.